### ISSUE TITLE
-t --title option not working

### ISSUE THREAD

**Issue by udiedrichsen** [crearlink/react-doc-creator#2]
It uses everytime just the default title.

**Comment by crearlink** [comment]
Hello Ulrich,

you should use quotes in case your title has blank spaces. I successfully tried some possibilities like:

```
-t "Shared Components"
-title Export
```
Some use examples are now available: https://github.com/crearlink/react-doc-creator#use-examples

Could you please try again and let me know if it meets your needs?

**Comment by udiedrichsen** [comment]
Hi,

Thanks for your fast support !

It works now perfect.

Cheers,

Uli
